Repository jenkinsci/mask-passwords-plugin, pull requests merged in 2020-04, with the labels that each got.

#21 Enable Release drafter in the repository
  .github/release-drafter.yml
  .github/workflows/changelog-draft.yml
Labels: internal

#20 [SECURITY-157] Fix global mask passwords config
  src/main/resources/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsBuildWrapper/global.jelly
Labels: bug

#19 Removed daring "view build parameters" value
  .gitignore
  pom.xml
  src/main/resources/com/michelin/cio/hudson/plugins/passwordparam/PasswordParameterValue/value.jelly
  src/main/resources/index.jelly
Labels: documentation

#22 Migrate plugin documentation from Wiki to GitHub
  README.md
  docs/CHANGELOG.old.md
  docs/README.md
  docs/images/add.svg
  docs/images/config-after.png
  docs/images/config-before.png
  docs/images/console-after.png
  docs/images/console-before.png
  docs/images/error.svg
  docs/images/global-settings.png
  docs/images/information.svg
  pom.xml
Labels: documentation
