Repository jenkinsci/mask-passwords-plugin, pull requests merged in 2023-01, with the labels that each got.

#32 Automate dependency updates
  .github/dependabot.yml
Labels: internal

#33 Publish incremental development artifacts
  .mvn/extensions.xml
  .mvn/maven.config
  pom.xml
  src/main/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsConfig.java
  src/main/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsOutputStream.java
Labels: internal

#30 Require Jenkins 2.361.4 or newer
  pom.xml
Labels: internal

#28 Automate plugin release
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .github/workflows/release-drafter.yml
  .mvn/maven.config
  pom.xml
  src/main/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsConfig.java
Labels: enhancement

#40 Skip two assertions on Windows
  src/test/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsWorkflowTest.java
Labels: test

#39 Use release drafter from cd workflow
  .github/workflows/changelog-draft.yml
Labels: chore
